# Generated by Django 4.2.2 on 2023-06-29 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.SmallIntegerField(default=0)),
                ('rating_text', models.CharField(default='Average', max_length=20)),
                ('rating_color', models.CharField(default='FFBA00', max_length=10)),
                ('aggregate_rating', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=36)),
                ('price_range', models.SmallIntegerField()),
                ('mezzo_provider', models.CharField(max_length=50)),
                ('order_deeplink', models.URLField(blank=True, null=True)),
                ('has_table_booking', models.BooleanField(default=False)),
                ('is_delivering_now', models.BooleanField(default=False)),
                ('opentable_support', models.BooleanField(default=False)),
                ('has_online_delivery', models.BooleanField(default=True)),
                ('include_bogo_offers', models.BooleanField(default=False)),
                ('average_cost_for_two', models.IntegerField()),
                ('switch_to_order_menu', models.BooleanField()),
                ('is_book_form_web_view', models.BooleanField(default=True)),
                ('book_form_web_view_url', models.URLField(blank=True, null=True)),
                ('is_table_reservation_supported', models.BooleanField(default=False)),
                ('cuisines', models.ManyToManyField(to='search.cuisine')),
                ('rating', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='search.rating')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('restaurant_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='search.restaurantdetail')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=100)),
                ('city_id', models.IntegerField()),
                ('zipcode', models.CharField(max_length=10)),
                ('locality', models.CharField(max_length=10)),
                ('latitude', models.CharField(max_length=60)),
                ('longitude', models.CharField(max_length=60)),
                ('country_id', models.SmallIntegerField()),
                ('restaurant_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.restaurantdetail')),
            ],
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=20)),
                ('offer', models.ManyToManyField(to='search.offer')),
                ('restaurant_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.restaurantdetail')),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=36)),
                ('restaurant_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.restaurantdetail')),
            ],
        ),
    ]
