# Generated by Django 4.2.2 on 2023-06-28 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=36)),
            ],
        ),
        migrations.CreateModel(
            name='FoodItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locality', models.CharField(max_length=10)),
                ('latitude', models.CharField(max_length=60)),
                ('longitude', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.SmallIntegerField(default=0)),
                ('rating_color', models.CharField(default='FFBA00', max_length=10)),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.fooditems')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=36)),
                ('price_range', models.SmallIntegerField()),
                ('mezzo_provider', models.CharField(max_length=50)),
                ('has_table_booking', models.BooleanField(default=False)),
                ('is_delivering_now', models.BooleanField(default=False)),
                ('opentable_support', models.BooleanField(default=False)),
                ('has_online_delivery', models.BooleanField(default=True)),
                ('include_bogo_offers', models.BooleanField(default=False)),
                ('average_cost_for_two', models.IntegerField()),
                ('switch_to_order_menu', models.BooleanField()),
                ('is_book_form_web_view', models.BooleanField(default=True)),
                ('book_form_web_view_url', models.URLField()),
                ('is_table_reservation_supported', models.BooleanField(default=False)),
                ('cuisines', models.ManyToManyField(to='search.cuisine')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.currency')),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.fooditems')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.location')),
                ('offers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.offer')),
                ('rating', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='search.rating')),
            ],
        ),
        migrations.AddField(
            model_name='fooditems',
            name='location',
            field=models.ManyToManyField(to='search.location'),
        ),
        migrations.AddField(
            model_name='fooditems',
            name='offer',
            field=models.ManyToManyField(to='search.offer'),
        ),
    ]
