# Generated by Django 4.2 on 2023-06-29 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_remove_currency_restaurant_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='name',
            field=models.TextField(),
        ),
    ]
